{
 "title": "CTFd",
 "time": { "from": "2022-04-23T08:00:00.000Z", "to": "2022-04-23T17:00:00.000Z" },
 "panels": [
  {
   "title": "Challenge Solves",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ctfd_challenge_solves_total", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Category Solves",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (category) (ctfd_challenge_solves_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Teams",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ctfd_teams_total", "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "Top 5 Teams",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, ctfd_team_points_total)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total Solves",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ctfd_challenge_solves_total)"
    }
   ]
  },
  {
   "title": "Average Solves",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(ctfd_team_solves_total)" }
   ]
  },
  {
   "title": "Solves per Hour",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 16, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ctfd_challenge_solves_total[60m]))"
    }
   ]
  },
  { "title": "Team Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Team Points",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
   "targets": [
    { "expr": "ctfd_team_points_total", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Team Challenge Solves",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
   "targets": [
    { "expr": "ctfd_team_solves_total", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Team Solves per Hour",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "increase(ctfd_team_solves_total[60m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Challenge Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Challenge Solves",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 40 },
   "targets": [
    { "expr": "ctfd_challenge_solves_total", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Challenge Value",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 49 },
   "targets": [
    { "expr": "ctfd_challenge_value", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Solves in past 60m",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "increase(ctfd_challenge_solves_total[60m])",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}