{
 "title": "General",
 "time": { "from": "now-9h", "to": "now" },
 "panels": [
  {
   "title": "Challenge Solves",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(ctfd_challenge_solves_total != 0)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total Solve Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ctfd_challenge_solves_total)"
    }
   ]
  },
  {
   "title": "Leaderboard",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(ctfd_team_points_total{hidden=\"False\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total Points",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ctfd_team_points_total{hidden=\"False\"})"
    }
   ]
  },
  {
   "title": "Points over Time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 16, "x": 8, "y": 11 },
   "targets": [
    {
     "expr": "ctfd_team_points_total{hidden=\"False\", banned=\"False\", name!=\"Platypwnies\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Category Solves",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (category) (ctfd_challenge_solves_total) != 0",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}